import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { newTegomin, notoSansJP } from "./utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[url('/hero_header/hero_header.svg')] bg-cover bg-fixed bg-center min-h-screen {'${notoSansJP.className} ${notoSansJP.variable} ${newTegomin.variable} antialiased'}">
        <div>
        {children}
        </div>
      </body>
    </html>
  );
}
