import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { newTegomin, notoSansJP } from "./utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'${notoSansJP.className} ${notoSansJP.variable} ${newTegomin.variable} antialiased'}>
        {children}
      </body>
    </html>
  );
}
