import type { Metadata } from 'next';
import Footer from '../components/common/footer';
import Header from '../components/common/header';
import MoveClouds from '../components/common/move_clouds';
import ReturnTopButton from '../components/common/return_top_button';
import { newTegomin, notoSansJP } from '../utils/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative min-h-screen ${notoSansJP.className} ${notoSansJP.variable} ${newTegomin.variable} antialiased`}
      >
        <div className="fixed inset-0 bg-[url('/hero_header/hero_header.svg')] bg-cover bg-center z-[-100]"></div>
        <div className="absolute -z-10">
          <MoveClouds />
        </div>

        <Header />
        <div className="mt-20 z-20">
          <div>
            <ReturnTopButton />
          </div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
